### ISSUE TITLE
Problem importing dae with texture

### ISSUE THREAD

**Issue by ronjunevaldoz** [libgdx/fbx-conv#126]
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: D:/Development/IntelliJProjects/flyffserverjava/resource/dae/mvr_acrguidepang-01.dds
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:140)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.GLTexture.createTextureData(GLTexture.java:185)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:103)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:95)

**Comment by mgsx-dev** [comment]
i think DDS file format isn't supported by libgdx

**Comment by ronjunevaldoz** [comment]
I see thanks!

**Comment by mgsx-dev** [comment]
@ronjunevaldoz please close the issue :-)
